@startuml Subscribe
!pragma teoz true

box "Client" #LightBlue
entity App
box "Secure Vault Library" #LightSkyBlue
participant "Vault Library" as SVC
end box
end box
box "Server" #LightSalmon
participant Server
database PostgreSQL
end box

activate App
    
    App -> SVC: secureVault.subscribeStorage()
    activate SVC
    SVC -> SVC: Create EventSourcePolyfill \n /files/storageSubscription
    SVC -> Server: GET files/storageSubscription
    Server -> PostgreSQL: Get data,epochtime,iv_data
    Server <-- PostgreSQL: Database Response
    Server -> Google: Get Signed URL
    {start1} Server <-- Google: Signed URL
    SVC <-- Server: Event 1 \n{message,storageUrl\nepochtime,iv_data}
    SVC <--SVC: Update storage
    {end1} Server -> PostgreSQL: Get data,epochtime,iv_data
    Server <-- PostgreSQL: Database Response
    Server -> Google: Get Signed URL
    {start2} Server <-- Google: Signed URL
    SVC <-- Server: Event ... \n{message,storageUrl\nepochtime,iv_data}
    SVC <--SVC: Update storage
    
    {end2} Server -> PostgreSQL: ...
    Server <-- PostgreSQL: ...
    SVC <--Server: Event n
    SVC <--SVC: Update storage
    App -> SVC: secureVault.unsubscribeStorage
    SVC -> Server: secureVault.unsubscribeStorage
deactivate App
{start1} <-> {end1}: 10 seconds
{start2} <-> {end2}: 10 seconds
@enduml