@startmindmap Server_Design
<style>
mindmapDiagram {
    Linecolor black
    arrow {
        LineColor black
    }
    node {
        RoundCorner 0

    }
}
</style>
* Src
** app.ts
** database.ts
** Controllers
*** filesController.ts
*** userController.ts
** Routes
*** filesRouter.ts
*** usersRouter.ts
** Models
*** userModel.ts
** Db
*** userQuery.ts
** Utils
*** config.ts 
*** FormDataUtils.ts
*** passport-config.ts
*** pbkdf2Async.ts
** i18n
*** i18n.ts
@endmindmap