@startuml SignUpV2
!pragma teoz true

box "Client" #LightBlue
entity App
box "Secure Vault Library" #LightSkyBlue
participant "Vault Library" as SVC
end box
end box
box "Server" #LightSalmon
participant Server
database PostgreSQL
end box

activate App
activate SVC
App -> SVC: secureVault.signUp(User)
SVC -> SVC: Generate Auth Key
SVC -> SVC: Set User.pwd with Auth \nKey
SVC -> Server: POST {User}
Server -> Server: Generate Server Salt
Server -> Server: Execute pbkdf2 on User.pwd\nwith Server Salt
Server -> Server: Set User.pwd with Server derived \nkey
Server -> PostgreSQL: Save User
Server <-- PostgreSQL: User Created Response
SVC <-- Server: Server Response
deactivate SVC
App <-- SVC: Server Response
deactivate App

{start} <-> {end} : 5 seconds timeout
@enduml